# Generated by Django 5.1.3 on 2024-11-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='checkout',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
