# Generated by Django 4.2 on 2024-11-27 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Enquiry_type', models.CharField(choices=[('general', 'General enquiry'), ('product', 'Product complaint'), ('order', 'Order Issue'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=25, verbose_name='Type of Enquiry')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
