# Generated by Django 4.2 on 2024-11-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='Enquiry_type',
            new_name='enquiry_type',
        ),
    ]
